### ISSUE TITLE
some readme files may need to be modified

### ISSUE THREAD

**Issue by ch2017322113** [BrainCog-X/Brain-Cog#45]
examples/Perception_and_Learning/img_cls/bp/readme

# The path may need to be changed to "cd examples/Perception_and_Learning/img_cls/bp"

cd examples/img_cls/bp 

# QGate->QGateGrad
python main.py --model dvs_convnet --node-type LIFNode --dataset dvsc10 --step 10 --batch-size 128 --act-fun QGate --device 0 

python main.py --model dvs_convnet --node-type LIFNode --dataset dvsc10 --step 10 --batch-size 128 --act-fun QGateGrad --device 0 
# name 'tonic' is not defined

**Comment by FloyedShen** [comment]
Thanks, 
we fixed the above problem in 31f860c36c602601f803770727d5f2d4212d4237. 
For tonic, if you are using a previous version, please refer to README.md and install https://github.com/BrainCog-X/tonic_braincog. If you are using the latest version, please install the official version directly from https://github.com/neuromorphs/tonic.
