### ISSUE TITLE
Import class name error

### ISSUE THREAD

**Issue by QianpengLi577** [BrainCog-X/Brain-Cog#98]
An error occurred while I was running brainSimMaq.py

`/Brain-Cog/examples/Multiscale_Brain_Structure_Simulation/MacaqueBrain$ python3 brainSimMaq.py `

`ImportError: cannot import name 'IFNodev1' from 'braincog.base.node.node'`

There is another issue, when I run `/Brain-Cog/examples/Multiscale_Brain_Structure_Simulation/Mouse_brain/Mouse_model.py`, cannot find `./mouse.mat`

**Comment by craree** [comment]
IFNodev1 has been removed from braincog/base/node/node .py and you can replace it with other nodes in the node.py, such as IFNode, LIFNode.
For Mouse_model.py, we have updated the code as well as the readme, and uploaded the corresponding files required for the code in the link to the readme.
For the brain simulation part, our latest code has changed significantly from the previous version, and is currently being modified and will be uploaded as soon as possible.
